[package]
name = "aoc-2022-day-10"
version = "0.1.0"
authors = ["Sebastian Ziebell <sebastian.ziebell@gmail.com"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
itertools = "0.10.5"
nom = "7.1"
