[package]
name = "aoc-2022-day-16"
version = "0.1.0"
authors = ["Sebastian Ziebell <sebastian.ziebell@gmail.com"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
array2d = "0.3.0"
itertools = "0.10.5"
peg = "0.8.1"
petgraph = "0.6.2"